version: "3.8"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/gdsc-server:${DOCKERHUB_IMAGE_TAG}
    container_name: gdsc-server
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    network_mode: host
