spring:
  config:
    activate:
      on-profile: "security"

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:default}
            client-secret: ${GITHUB_CLIENT_SECRET:default}
            redirect-uri: "https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"

jwt:
  token:
    ACCESS_TOKEN:
      secret: ${JWT_ACCESS_TOKEN_SECRET:}
      expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
    REFRESH_TOKEN:
      secret: ${JWT_REFRESH_TOKEN_SECRET:}
      expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800}
    EMAIL_VERIFICATION_TOKEN:
      secret: ${JWT_EMAIL_VERIFICATION_TOKEN_SECRET:}
      expiration-time: ${JWT_EMAIL_VERIFICATION_TOKEN_EXPIRATION_TIME:1800}
  issuer: ${JWT_ISSUER:}

auth:
  username: ${BASIC_AUTH_USERNAME:default}
  password: ${BASIC_AUTH_PASSWORD:default}
