spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
    include:
      - redis
      - storage
      - security
      - swagger

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: debug

gmail:
  id: ${GMAIL_ID}
  password: ${GMAIL_PASSWORD}
