spring:
  config:
    activate:
      on-profile: "security"

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:default}
            client-secret: ${GITHUB_CLIENT_SECRET:default}
            redirect-uri: "https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"

jwt:
  token:
    ACCESS_TOKEN:
      secret: ${JWT_ACCESS_TOKEN_SECRET:3q2tqat432wtq23tq2387trq8723yrhfi87a2wuyh3efo7qa2y3fho2qa}
      expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:7200}
    REFRESH_TOKEN:
      secret: ${JWT_REFRESH_TOKEN_SECRET:3248oqy478ryq327owyhtfq2gaw3eygfq23867gq2o87}
      expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:604800}
    EMAIL_VERIFICATION_TOKEN:
      secret: ${JWT_EMAIL_VERIFICATION_TOKEN_SECRET:235872q3ywhtf87q243yt98qop42y3whtg8oiq92ayh4gq2g}
      expiration-time: ${JWT_EMAIL_VERIFICATION_TOKEN_EXPIRATION_TIME:1800}
  issuer: ${JWT_ISSUER:}

auth:
  username: ${BASIC_AUTH_USERNAME:default}
  password: ${BASIC_AUTH_PASSWORD:default}
