spring:
  config:
    activate:
      on-profile: "sentry"

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  environment: ${spring.profiles.active:local}
  send-default-pii: true
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: debug

docker:
  tag: ${DOCKER_IMAGE_TAG:}
