spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
      prod: "prod, datasource"
    include:
      - redis
      - security
      - actuator
      - discord
      - email
      - payment

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: debug
