spring:
  config:
    activate:
      on-profile: "local"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        highlight_sql: ${HIGHLIGHT_SQL:true}
    defer-datasource-initialization: true
    open-in-view: false

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: ${LOG_LEVEL_API:debug}
    com.gdschongik.gdsc.infra.feign: ${LOG_LEVEL_FEIGN:debug}
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_HIBERNATE_BIND:trace}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:debug}
    org.kohsuke.github: ${LOG_LEVEL_KOHSUKE_GITHUB:debug}
    org.hibernate.stat: ${LOG_LEVEL_HIBERNATE_STAT:info}
