spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: info
    com.gdschongik.gdsc.infra.feign: debug
