spring:
  config:
    activate:
      on-profile: "sentry"

sentry:
  dsn: ${SENTRY_DSN:}
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647
  environment: ${spring.profiles.active:local}
