management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
      base-path: /gdsc-actuator
    jmx:
      exposure:
        exclude: "*"
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
