spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource, discord"
      dev: "dev, datasource, discord"
    include:
      - redis
      - security
      - swagger
      - actuator

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: debug
