spring:
  profiles:
    group:
      test: "test"
      local: "local, datasource"
      dev: "dev, datasource"
    include:
      - redis
      - security
      - swagger
      - actuator
      - discord

logging:
  level:
    com.gdschongik.gdsc.domain.*.api.*: debug

email:
  google:
    login-email: ${GOOGLE_LOGIN_EMAIL}
    password: ${GOOGLE_PASSWORD}
